* GameGrid
  animation of stupid game whose name I don't remember, using <TransitionGroup>

  transitionGroup, just like Transition, takes a child function, this time,
  it is expected to be map(), taking some elements and mapping them to <transition>
  or <CSStransition> elements.

  for this component, it'll have a state, where I'll store all the info on the
  grid elements. Each of them will be a dict containing all the info
  necessary to reconstruct the item, including an id that specifies it's position
  on the grid.

  There's going to be a function, handleClick, that manages two possibilities:
  + no place to go: the item bounces in place.
  + at least one place to go: pick a direction at random, and slide there.
  
  we'll change something as apparently what i had in mind is difficult with the
  tools i'm using. There'll be no movement fron one side to the other in the
  grid. instead, the items will shrink in place, and reappear on another, random
  position.

  since what we'll do does not require empty neighbors, the conditional is not
  necessary.

  So here's what's going to happen: the list of items will be sorted according to
  the position of the items in the grid. Each click picks a random position within
  the list, inserts the element there, and removes the original. This way, when
  the component is re-rendered, this will trigger the appear/disappear animations.
